"""Static project page, generated by both public and raw-data pipelines."""


def render_page(summary: dict, scenario: dict) -> str:
    od = summary["od_departure_bus_event_window"]
    bus = summary["bus_boardings"]["event_window_18_23"]
    tpss = summary["tpss_supply"]["event_window_18_23"]
    return f"""<!doctype html>
<html lang="ko">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="여의도 불꽃축제 귀가 교통을 수요·운행·이동시간으로 분석하고 외곽 환승거점 셔틀을 제안한 교통공학 졸업작품.">
  <title>여의도 불꽃축제 귀가 교통 분석 · 윤찬혁</title>
  <style>
    :root {{ --ink:#17231f; --muted:#52645c; --paper:#f7f5ef; --green:#185c49; --line:#d4ded8; }}
    * {{ box-sizing:border-box; }}
    body {{ margin:0; color:var(--ink); background:var(--paper); font:16px/1.8 "Malgun Gothic",sans-serif; word-break:keep-all; overflow-wrap:anywhere; }}
    a {{ color:var(--green); text-underline-offset:4px; }}
    a:focus-visible {{ outline:3px solid #b1d755; outline-offset:5px; }}
    header,main,footer {{ width:min(1080px,calc(100% - 40px)); margin:auto; }}
    nav {{ display:flex; flex-wrap:wrap; gap:20px; padding:20px 0; border-bottom:1px solid var(--line); font-size:14px; }}
    .hero {{ padding:44px 0 28px; max-width:850px; }}
    .eyebrow {{ color:var(--green); font-size:14px; font-weight:700; }}
    h1 {{ font-size:clamp(30px,4.2vw,48px); line-height:1.3; letter-spacing:-.04em; margin:12px 0 22px; }}
    h2 {{ margin:0 0 16px; font-size:clamp(24px,3vw,32px); line-height:1.4; letter-spacing:-.03em; }}
    h3 {{ font-size:18px; margin:0 0 8px; }}
    p {{ margin:0 0 16px; }}
    section {{ padding:36px 0; border-top:1px solid var(--line); }}
    .metrics {{ display:grid; grid-template-columns:repeat(3,minmax(0,1fr)); gap:16px; }}
    .metric {{ padding:24px; background:white; border-top:3px solid var(--green); }}
    .metric b {{ display:block; color:var(--green); font-size:36px; line-height:1.3; margin:12px 0; }}
    .metric span,.note,figcaption {{ color:var(--muted); font-size:14px; }}
    .grid {{ display:grid; grid-template-columns:repeat(2,minmax(0,1fr)); gap:24px; }}
    figure {{ margin:0; background:white; padding:16px; border:1px solid var(--line); }}
    img {{ width:100%; height:auto; display:block; }}
    figcaption {{ padding-top:12px; }}
    .flow {{ display:flex; flex-wrap:wrap; align-items:center; gap:14px; margin:24px 0; }}
    .flow span {{ border:1px solid var(--line); padding:12px 20px; background:white; }}
    .flow .hubs {{ border-color:var(--green); color:var(--green); font-weight:700; }}
    .callout {{ padding:24px; background:#e8efe9; }}
    code {{ background:#e5ebe6; padding:3px 6px; overflow-wrap:anywhere; }}
    pre {{ white-space:pre-wrap; padding:20px; background:#e5ebe6; }}
    pre code {{ padding:0; }}
    summary {{ cursor:pointer; color:var(--green); font-weight:700; }}
    details > div {{ padding-top:20px; }}
    footer {{ padding:24px 0 40px; border-top:1px solid var(--line); font-size:14px; }}
    @media(max-width:700px) {{ .metrics,.grid {{ grid-template-columns:1fr; }} .hero {{ padding-top:28px; }} section {{ padding:28px 0; }} .metric {{ padding:20px; }} }}
  </style>
</head>
<body>
<header>
  <nav aria-label="관련 페이지"><a href="https://yoon-chan-hyeok.github.io/">윤찬혁 포트폴리오</a><a href="https://github.com/yoon-chan-hyeok/yeouido-festival-mobility-analysis">GitHub · 코드와 분석 방법 ↗</a></nav>
  <div class="hero">
    <p class="eyebrow">교통공학 졸업작품 · 2023 서울세계불꽃축제 사례</p>
    <h1>불꽃축제 뒤 귀가가 늦어진 이유</h1>
    <p>직접 겪은 귀가 지연에서 출발해, 여의도를 떠나는 수요와 대중교통 운행을 함께 분석했습니다. 이용 수요가 늘어난 시간에 버스 정차횟수는 줄었습니다. 이를 바탕으로 외곽 철도 환승거점과 연결하는 셔틀을 제안했습니다.</p>
    <p class="note">행사일과 정상 토요일을 비교한 사례 분석입니다. 셔틀 운영안의 효과는 아직 검증하지 않았습니다.</p>
  </div>
</header>
<main>
  <section aria-labelledby="result-title">
    <h2 id="result-title">수요는 늘고, 정차횟수는 줄었습니다</h2>
    <p>10월 7일 18:00~23:59의 합계를 정상 토요일과 비교했습니다. 이동시간은 이 구간의 통행량 가중평균입니다.</p>
    <div class="metrics">
      <div class="metric">버스 OD 이동시간<b>+{od['difference_minutes']:.2f}분</b><span>여의도 → 서울 다른 지역<br>통행량 가중평균 {od['normal_weighted_avg_duration_minutes']:.2f} → {od['event_weighted_avg_duration_minutes']:.2f}분</span></div>
      <div class="metric">버스 승차 관측치<b>+{bus['target_minus_normal']/bus['normal_avg']*100:.1f}%</b><span>정상 평균 {bus['normal_avg']:,.1f} → 행사일 {bus['target']:,.0f}<br>교통카드 거래내역 기반 집계</span></div>
      <div class="metric">버스 정류장 정차횟수<b>{tpss['target_minus_normal']/tpss['normal_avg']*100:.1f}%</b><span>정상 평균 {tpss['normal_avg']:,.1f} → 행사일 {tpss['target']:,.0f}<br>TPSS 관측값 · 차량 대수 아님</span></div>
    </div>
    <p class="note">OD는 출발지·도착지 통행입니다. 이동시간 차이에는 목적지와 통행 구성의 차이도 포함되며, 동일 경로의 순수 지연이나 인과효과를 뜻하지 않습니다.</p>
  </section>
  <section>
    <h2>수요·운행·이동 결과를 나눠 봤습니다</h2>
    <p>방문객이 얼마나 늘었는지만으로는 교통 운영을 판단하기 어려웠습니다. SKT OD·체류인구, 서울시 버스·지하철 이용 자료, TPSS 정차횟수를 시간대별로 맞추고, GIS로 분석 지역을 확인했습니다. 서로 단위가 다른 자료는 각각 평상시와 비교했습니다.</p>
    <div class="grid">
      <figure><img src="outputs/figures/actual_demand_supply_change.svg" alt="행사일 버스와 지하철 승차 관측치 증가 및 정차횟수 감소"><figcaption>선정한 정류장·역의 교통카드 승차 집계와 정차횟수를 비교했습니다. 승차 건수는 고유 이용자 수와 다릅니다.</figcaption></figure>
      <figure><img src="outputs/figures/actual_od_bus_duration.svg" alt="여의도 출발 서울 다른 지역행 버스 OD의 시간대별 가중평균 이동시간"><figcaption>OD별 통행량을 가중치로 이동시간을 계산했습니다. 시간대별 차이를 확인할 수 있습니다.</figcaption></figure>
    </div>
    <p class="note">OD·체류인구와 대중교통 자료는 확보 기간이 달라 정상 토요일의 날짜 구성이 다릅니다. 비교군과 변수 정의는 <a href="https://github.com/yoon-chan-hyeok/yeouido-festival-mobility-analysis/blob/main/docs/METHODOLOGY.md">분석 방법</a>에 공개했습니다.</p>
  </section>
  <section>
    <h2>외곽 환승거점으로 귀가 수요 분산</h2>
    <p>졸업작품 발표에서는 여의도에 집중된 수요를 당산·공덕·노량진역으로 옮기는 셔틀을 제안했습니다. 여의도 혼잡 구역 밖의 철도 환승역을 고르고, 귀가 방향과 셔틀 반복 운행 거리를 함께 고려했습니다.</p>
    <div class="flow" aria-label="셔틀 운영 개념도">
      <span>여의도 귀가 수요</span><b aria-hidden="true">→</b><span>사전 대기 셔틀</span><b aria-hidden="true">→</b><span class="hubs">당산 · 공덕 · 노량진</span><b aria-hidden="true">→</b><span>철도 환승</span>
    </div>
    <div class="callout">
      <h3>정차횟수가 평소 수준으로 돌아온다면?</h3>
      <p>공개본 재분석에서는 행사일 수요를 그대로 두고 정차횟수만 바꾸는 계산을 추가했습니다. 정차 1회당 승차 관측치의 부담은 평상시 대비 <strong>{scenario['current_stress_index']:.2f}배</strong>였고, 정차횟수 회복 가정에서도 <strong>{scenario['stress_index_after_normal_supply_restore']:.2f}배</strong>가 남았습니다.</p>
      <p class="note">수요 분산의 필요성을 검토하는 산술적 stress test입니다. 실제 증차·셔틀 수송 효과나 시간 절감을 예측한 값은 아닙니다. <a href="outputs/reports/supply_recovery_stress_test.json">계산식과 입력값</a></p>
    </div>
  </section>
  <section>
    <h2>분석에서 확인한 것과 남은 것</h2>
    <p>초기에는 평시 첨두 대비 초과 교통량과 Isotonic Regression으로 지체의 증가 방향을 반영했습니다. 현재 확보한 행사 사례는 한 건이어서 새로운 행사에 대한 예측 성능은 주장하지 않습니다. 공개본은 관측 결과와 운영 가설에 초점을 맞췄습니다.</p>
    <details><summary>공간 범위와 데이터 품질 확인</summary><div>
      <figure><img src="outputs/figures/actual_gis_scope.svg" alt="행정경계와 여의도 정류장 분석 범위" loading="lazy"><figcaption>2017년 행정경계와 2019년 정류장 위치를 2023년 교통자료에 적용했습니다.</figcaption></figure>
      <p>정류장 59개 ID 중 TPSS는 54개가 연결됐습니다. 버스 이용 자료는 고유 정류장명 40개 중 32개가 관측됐습니다. 누락과 중복은 <a href="outputs/tables/join_audit.csv">결합 검증표</a>에 남겼습니다.</p>
    </div></details>
    <p>셔틀 운영을 결정하려면 실제 노선·차량·통제 자료, 승하차 공간과 환승역 수용 능력을 추가로 검토해야 합니다. 지금의 결과만으로 최적 거점이나 운영 효과를 확정할 수는 없습니다.</p>
  </section>
  <section>
    <h2>공개 데이터로 다시 실행하기</h2>
    <p>Python 3.10 이상에서 외부 패키지 없이 결과 표·그림·이 페이지를 다시 만들 수 있습니다. 원자료는 포함하지 않고 날짜·시간 단위 집계본을 공개했습니다.</p>
    <pre><code>python reproduce_public.py
python -m unittest discover -s tests
python validate_release.py</code></pre>
    <a href="https://github.com/yoon-chan-hyeok/yeouido-festival-mobility-analysis">저장소에서 데이터·코드·상세 문서 보기 ↗</a>
  </section>
</main>
<footer>윤찬혁 · 교통공학 졸업작품 | <a href="https://yoon-chan-hyeok.github.io/">전체 프로젝트</a></footer>
</body></html>
"""
